# -*- coding: utf-8 -*-
"""DSPL Group B15 - EDA and Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REEKi24By-r3yMwEIg4X1bmrGBLQ9kps

#Test data

#Exploratory data analysis - Before Preprocessing
"""

#import the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load the dataset
test_df = pd.read_csv('test.csv')

#Display basic information
test_df.head()

#check number of observations and columns
test_df.shape

#Check data types
test_df.dtypes

test_df.info()

#Descriptive statistics
test_df.describe(include = 'all')

#check missing values
test_df.isnull().sum()

#Finding duplicate values
test_df.duplicated().sum()

#finding unique values in outlet_city in Test data
unique_outlet_city = test_df['outlet_city'].unique()
length_Test = len(unique_outlet_city)
print(unique_outlet_city)
length_Test

"""#Univariate analysis"""

#Finding distribution of luxury sales
test_df['luxury_sales'] = pd.to_numeric(test_df['luxury_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(test_df['luxury_sales'], color='lightpink')
plt.title('Distribution of luxury_sales')
plt.show()

#Finding distribution of dry sales
test_df['dry_sales'] = pd.to_numeric(test_df['dry_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(test_df['dry_sales'], color='lightblue')
plt.title('Distribution of dry_sales')
plt.show()

#Finding distribution of fresh sales
test_df['fresh_sales'] = pd.to_numeric(test_df['fresh_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(test_df['fresh_sales'], color='lightgreen')
plt.title('Distribution of fresh_sales')
plt.show()

"""#Multivariate analysis"""

#Scatter plot - Luxury sales Vs. Dry sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='dry_sales', data=test_df, color='lightpink')
plt.title('Scatter plot - Luxury sales Vs.  Dry sales')
plt.show()

#Scatter plot - Luxury sales Vs. Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='fresh_sales', data=test_df, color='lightblue')
plt.title('Scatter plot - Luxury sales Vs.  Fresh sales')
plt.show()

#Scatter plot - Dry sales Vs. Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='dry_sales', y='fresh_sales', data=test_df, color='lightgreen')
plt.title('Scatter plot - Dry sales Vs.  Fresh sales')
plt.show()

#Luxury sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='luxury_sales', data=test_df, color='lightpink')
plt.xticks(rotation=90)
plt.title('Luxury sales Vs. Outlet city')

#Dry sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='dry_sales', data=test_df, color='lightblue')
plt.xticks(rotation=90)
plt.title('Dry sales Vs. Outlet city')

#Fresh sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='fresh_sales', data=test_df, color='lightgreen')
plt.xticks(rotation=90)
plt.title('Fresh sales Vs. Outlet city')

#correlation matrix
corr_matrix = test_df.select_dtypes(include=['number']).corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation matrix')
plt.show()

"""#Data Preprocessing"""

#Change the data types to numeric
test_df['luxury_sales'] = pd.to_numeric(test_df['luxury_sales'], errors = 'coerce')
test_df['dry_sales'] = pd.to_numeric(test_df['dry_sales'], errors = 'coerce')
test_df['fresh_sales'] = pd.to_numeric(test_df['fresh_sales'], errors = 'coerce')

#Check for missing values
test_df.isnull().sum()

#Find the rows that have missing values
missing_rows = test_df[test_df.isnull().any(axis=1)]
missing_rows

test_check = pd.read_csv('test.csv')
test_check[test_check['Customer_ID'].isin([10364,4059,28662,28664])]

#convert textual figures into numbers
test_df.loc[test_df['Customer_ID']== 10364, 'luxury_sales'] = 760
test_df.loc[test_df['Customer_ID']== 4059, 'luxury_sales'] = 815
test_df.loc[test_df['Customer_ID']== 28662, 'fresh_sales'] = 9000
test_df.loc[test_df['Customer_ID']== 28664, 'dry_sales'] = 3700

#Check for missing values after cleaning
test_df.isnull().sum()

#change Customer_ID to object data type
test_df['Customer_ID'] = test_df['Customer_ID'].astype(str)
test_df.dtypes

#finding unique values
#outlet_city
unique_outlet_city = test_df['outlet_city'].unique()
length_Test = len(unique_outlet_city)

# Print the length of unique outlet cities
print(f"Number of unique outlet cities: {length_Test}")
print(f"Unique outlet_city: {unique_outlet_city}")

city_corrections = {
    'PeliyagodA':'Peliyagoda',
    'Madawachiya':'Medawachchiya',
    'batticaloa':'Batticaloa',
    'kalmunai' : 'Kalmunai',
    'Trincomale':'Trincomalee',
    'MoraTuwa':'Moratuwa'

}

test_df['outlet_city'] = test_df['outlet_city'].replace(city_corrections)

#finding unique values
#outlet_city
unique_outlet_city = test_df['outlet_city'].unique()
length_Test = len(unique_outlet_city)

# Print the length of unique outlet cities
print(f"Number of unique outlet cities: {length_Test}")
print(f"Unique outlet_city: {unique_outlet_city}")

#box plot for luxury sales
plt.figure(figsize=(10,6))
sns.boxplot(x='luxury_sales', data=test_df, color='lightpink')

#Handling outliers in luxury sales
Q1 = test_df['luxury_sales'].quantile(0.25)
Q3 = test_df['luxury_sales'].quantile(0.75)
IQR = Q3 - Q1

#outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

#filter the outliers
test_df = test_df[(test_df['luxury_sales'] >= lower_bound) & (test_df['luxury_sales'] <= upper_bound)]

#box plot for luxury sales after removing outliers
plt.figure(figsize=(10,6))
sns.boxplot(x='luxury_sales', data=test_df, color='lightpink')

#box plot for dry sales
plt.figure(figsize=(10,6))
sns.boxplot(x='dry_sales', data=test_df, color='lightblue')

#box plot for fresh sales
plt.figure(figsize=(10,6))
sns.boxplot(x='fresh_sales', data=test_df, color='lightgreen')

"""#Exploratory Data Analysis - After Preprocessing

#Univariate Analysis
"""

#distribution of luxury sales
plt.figure(figsize=(10,6))
sns.histplot(test_df['luxury_sales'], color='lightpink')
plt.title('Distribution of luxury_sales')
plt.show()

#distribution of dry sales
plt.figure(figsize=(10,6))
sns.histplot(test_df['dry_sales'], color='lightblue')
plt.title('Distribution of dry_sales')
plt.show()

#distribution of fresh sales
plt.figure(figsize=(10,6))
sns.histplot(test_df['fresh_sales'], color='lightgreen')
plt.title('Distribution of fresh_sales')
plt.show()

"""#Multi-Variate Analysis"""

#Scatter plot for Luxury Sales Vs. Dry sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='dry_sales', data=test_df, color='lightpink')
plt.title('Scatter plot - Luxury sales Vs.  Dry sales')
plt.show()

#Scatter plot for Luxury sales Vs Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='fresh_sales', data=test_df, color='lightblue')
plt.title('Scatter plot - Luxury sales Vs.  Fresh sales')
plt.show()

#Scatter plot for dry sales Vs fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='dry_sales', y='fresh_sales', data=test_df, color='lightgreen')
plt.title('Scatter plot - Dry sales Vs.  Fresh sales')
plt.show()

#Luxury sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='luxury_sales', data=test_df, color='lightpink')
plt.xticks(rotation=90)
plt.title('Luxury sales Vs. Outlet city')

#Dry sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='dry_sales', data=test_df, color='lightblue')
plt.xticks(rotation=90)
plt.title('Dry sales Vs. Outlet city')

#Fresh sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='fresh_sales', data=test_df, color='lightgreen')
plt.xticks(rotation=90)
plt.title('Fresh sales Vs. Outlet city')

#correlation matrix
corr_matrix = test_df.select_dtypes(include=['number']).corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation matrix')
plt.show()

#save cleaned test data as a new csv file
test_df.to_csv('cleaned_test.csv', index=False)

"""#Feature Engineering"""

#Encoding outlet_city so that it is considered as a numeric variable
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
test_df['outlet_city'] = test_df['outlet_city'].astype('category')
test_df['outlet_city_encoded'] = test_df['outlet_city'].cat.codes
test_df.head()

"""#Train data

#Exploratory Data Analysis - Before Preprocessing
"""

#read csv files
train_df = pd.read_csv('traincsv.csv')

#displaying first five rows of the train dataset
train_df.head()

# Program to print all the column names of the train dataset
list(train_df.columns)

#Number of rows and columns in train dataset
train_df.shape

#Check data types
train_df.dtypes

train_df.info()

#Descriptive statistics of the train dataset
train_df.describe(include='all')

#Check for missing values in Train datasets
missing_train = train_df.isnull().sum()

#selects specific columns from a DataFrame
subset_cols = ['Customer_ID', 'luxury_sales', 'fresh_sales', 'dry_sales', 'cluster_catgeory']
subset_train_df = train_df[subset_cols]

#Calculate missing values for each column
missing_values = subset_train_df.isnull().sum()

#Create the bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x=missing_values.index, y=missing_values.values)

#Customize the chart
plt.title('Missing Values in Selected Columns (Train Dataset)')
plt.xlabel('Columns')
plt.ylabel('Number of Missing Values')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

#Number of duplicates
train_df.duplicated().sum()

#finding unique values in outlet_city in Train data
unique_outlet_city = train_df['outlet_city'].unique()
length_Train = len(unique_outlet_city)
print(unique_outlet_city)
length_Train

"""#Univariate Analysis"""

#Finding distribution of luxury sales
train_df['luxury_sales'] = pd.to_numeric(train_df['luxury_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(train_df['luxury_sales'], color='lightpink')
plt.title('Distribution of luxury_sales')
plt.show()

#Finding distribution of dry sales
train_df['dry_sales'] = pd.to_numeric(train_df['dry_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(train_df['dry_sales'], color='lightblue')
plt.title('Distribution of dry_sales')
plt.show()

#Finding distribution of fresh sales
train_df['fresh_sales'] = pd.to_numeric(train_df['fresh_sales'], errors = 'coerce')

plt.figure(figsize=(10,6))
sns.histplot(train_df['fresh_sales'], color='lightgreen')
plt.title('Distribution of fresh_sales')
plt.show()

#frequency distribution for cluster variable
plt.figure(figsize=(10,6))
sns.countplot(x='cluster_catgeory', data=train_df, color='orange')
plt.title('Frequency distribution for cluster_category')

"""#Multi-Variate Analysis"""

#Scatter plot - Luxury sales Vs. Dry sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='dry_sales', data=train_df, color='lightpink')
plt.title('Scatter plot - Luxury sales Vs.  Dry sales')
plt.show()

#Scatter plot - Luxury sales Vs. Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='fresh_sales', data=train_df, color='lightblue')
plt.title('Scatter plot - Luxury sales Vs.  Fresh sales')
plt.show()

#Scatter plot - Dry sales Vs. Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='dry_sales', y='fresh_sales', data=train_df, color='lightgreen')
plt.title('Scatter plot - Dry sales Vs.  Fresh sales')
plt.show()

#Luxury sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='luxury_sales', data=train_df, color='lightpink')
plt.xticks(rotation=90)
plt.title('Luxury sales Vs. Outlet city')

#Dry sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='dry_sales', data=train_df, color='lightblue')
plt.xticks(rotation=90)
plt.title('Dry sales Vs. Outlet city')

#Fresh sales Vs. Outlet city
plt.figure(figsize=(12,6))
sns.boxplot(x='outlet_city', y='fresh_sales', data=train_df, color='lightgreen')
plt.xticks(rotation=90)
plt.title('Fresh sales Vs. Outlet city')

#Luxury sales Vs Cluster
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='luxury_sales', data=train_df, color='lightpink')

#Dry sales Vs Clusters
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='dry_sales', data=train_df, color='lightblue')

#Fresh sales Vs Clusters
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='fresh_sales', data=train_df, color='lightgreen')

#correlation matrix
corr_matrix = train_df.select_dtypes(include=['number']).corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation matrix')
plt.show()

"""#Preprocessing"""

#missing values
train_df.isnull().sum()

#data type
train_df.dtypes

#display rows with missing values
missing_rows = train_df[train_df.isnull().any(axis=1)]
missing_rows

"""#customer_id
Justification: Customer ID is A primary key, which uniquely identifies each record. By filling missing 'Customer_ID' values with new unique values, you retain all the information, also UUIDs are more robust if you need to ensure absolute uniqueness.
"""

#display the rows with customer_id is null
train_df[train_df['Customer_ID'].isnull()]

import uuid

for index, row in train_df[train_df['Customer_ID'].isnull()].iterrows():
       train_df.loc[index, 'Customer_ID'] = str(uuid.uuid4())

import hashlib

for index, row in train_df[train_df['Customer_ID'].isnull()].iterrows():
       combined_info = str(row['name']) + str(row['email'])
       hashed_id = hashlib.sha256(combined_info.encode()).hexdigest()
       train_df.loc[index, 'Customer_ID'] = hashed_id

#missing values in customer_id
train_df.isnull().sum()

"""#outlet_city
Correcting the errors in spelling of the dataset.As we can see, finding 'Anuradhapura', 'Medawachchiya' as missing values.
"""

#display the rows where outlet_city is null
train_df[train_df['outlet_city'].isnull()]

#finding unique values
#outlet_city
unique_outlet_city = train_df['outlet_city'].unique()
length_Train = len(unique_outlet_city)

# Print the length of unique outlet cities
print(f"Number of unique outlet cities: {length_Train}")
print(f"Unique outlet_city: {unique_outlet_city}")

train_df['outlet_city'] = train_df['outlet_city'].str.title()
city_corrections = {
    'PeliyagodA':'Peliyagoda',
    'Madawachiya':'Medawachchiya',
    'batticaloa':'Batticaloa',
    'Trincomale':'Trincomalee',
    'MoraTuwa':'Moratuwa'

}

train_df['outlet_city'] = train_df['outlet_city'].replace(city_corrections)

#finding unique values which had spelling errors been rectified
#outlet_city
unique_outlet_city = train_df['outlet_city'].unique()
length_Train = len(unique_outlet_city)
train_cities = set(train_df['outlet_city'].unique())

#finding unique values
#outlet_city
unique_outlet_city = test_df['outlet_city'].unique()
length_Test = len(unique_outlet_city)
test_cities = set(test_df['outlet_city'].unique())

missing_cities = test_cities - train_cities
print("Missing outlet_city values in train_df:", missing_cities)

# Print the length of unique outlet cities
print(f"Number of unique outlet cities: {length_Train}")
print(train_cities)

# Print the length of unique outlet cities
print(f"Number of unique outlet cities: {length_Test}")
print(test_cities)

#dropping the two null values in outlet_city
train_df = train_df.dropna(subset=['outlet_city'])

#missing values
train_df.isnull().sum()

"""#luxury_sales, fresh_sales, dry_sales
Median imputation is relatively simple to implement and computationally efficient.Sales data oftem falls a skewed distribution, where the majority of sales might fall within a range, with a few exceptionally high sales. The median is a better representation of the central tendency in skewed data compared to the mean.
"""

#Ensure no negative values
df = train_df[(train_df['luxury_sales'] >= 0) & (train_df['fresh_sales'] >= 0) & (train_df['dry_sales'] >= 0)]

#Median Imputation for luxury_sales by taking the median sales for the relevant outlet_city
median_luxury_sales = train_df.groupby('outlet_city')['luxury_sales'].median()

#Fill missing values
train_df['luxury_sales'] = train_df.apply(
    lambda row: median_luxury_sales[row['outlet_city']] if pd.isnull(row['luxury_sales']) else row['luxury_sales'],
    axis=1)

#check for missing values in the luxury_sales column
missing_luxury_sales = train_df[train_df['luxury_sales'].isnull()]
missing_luxury_sales

#Median Imputation for dry_sales by taking the median sales for the relevant outlet_city
median_dry_sales = train_df.groupby('outlet_city')['dry_sales'].median()

#Fill missing values
train_df['dry_sales'] = train_df.apply(
    lambda row: median_dry_sales[row['outlet_city']] if pd.isnull(row['dry_sales']) else row['dry_sales'],
    axis=1)

#check for missing values in the dry_sales column
missing_dry_sales = train_df[train_df['dry_sales'].isnull()]
missing_dry_sales

#Median Imputation for fresh_sales by taking the median sales for the relevant outlet_city
median_fresh_sales = train_df.groupby('outlet_city')['fresh_sales'].median()

#Fill missing values
train_df['fresh_sales'] = train_df.apply(
    lambda row: median_fresh_sales[row['outlet_city']] if pd.isnull(row['fresh_sales']) else row['fresh_sales'],
    axis=1)

#check for missing values in the fresh_sales column
missing_fresh_sales = train_df[train_df['fresh_sales'].isnull()]
missing_fresh_sales

#missing values as a percentage
missing_values_percentage = (train_df.isnull().sum() / len(train_df)) * 100
missing_values_percentage

#drop the null rows
train_df.dropna(inplace=True)
train_df.isnull().sum()

#box plot of luxury sales
plt.figure(figsize=(10,6))
sns.boxplot(x='luxury_sales', data=train_df, color='lightpink')

#handling outliers in luxury_sale using IQR
Q1 = df['luxury_sales'].quantile(0.25)
Q3 = df['luxury_sales'].quantile(0.75)
IQR = Q3 - Q1

#Outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

#Filter out the outliers
df_cleaned = df[(df['luxury_sales'] >= lower_bound) & (df['luxury_sales'] <= upper_bound)]

#box plot of luxury sales after cleaning
plt.figure(figsize=(10,6))
sns.boxplot(x='luxury_sales', data=df_cleaned, color='lightpink')

"""#Cluster_catgeory
Drop the null values, since it is a dependant variable we can't decide its results by assumptions.
"""

#Convert the 'cluster_catgeory' column to strings for consistency
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].astype(str)

#Check the unique values from the cluster category feature
train_df['cluster_catgeory'].unique()

#Inconsistency in dataset - replace 6\ with 6
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('6\\', '6')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('1.0', '1')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('2.0', '2')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('3.0', '3')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('4.0', '4')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('5.0', '5')
train_df['cluster_catgeory'] = train_df['cluster_catgeory'].str.replace('6.0', '6')

#Check the unique values from the cluster category feature
train_df['cluster_catgeory'].unique()

#Drop the rows in cluster 89,95,98,100
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '89'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '95'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '98'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '99'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '100'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '89.0'].index)
train_df= train_df.drop(train_df[train_df['cluster_catgeory'] == '100.0'].index)

#remove null values
train_df = train_df.dropna(subset=['cluster_catgeory'])

#unique values in cluster
unique_cluster = train_df['cluster_catgeory'].unique()
length_cluster = len(unique_cluster)
print(unique_cluster)
length_cluster

#missing values
train_df.isnull().sum()

#remove duplicates
train_df.drop_duplicates(inplace=True)

#Validate Data
assert (train_df['luxury_sales'] >= 0).all()
assert (train_df['fresh_sales'] >= 0).all()
assert (train_df['dry_sales'] >= 0).all()

#boxplot for dry sales
plt.figure(figsize=(10,6))
sns.boxplot(x='dry_sales', data=train_df, color='lightblue')

#boxplot for fresh sales
plt.figure(figsize=(10,6))
sns.boxplot(x='fresh_sales', data=train_df, color='lightgreen')

"""#Exploratory Data Analysis - After Preprocessing

#Univariate Analysis
"""

#distribution of luxury sales
plt.figure(figsize=(10,6))
sns.histplot(train_df['luxury_sales'], color='lightpink')
plt.title('Distribution of luxury_sales')
plt.show()

#distribution of dry sales
plt.figure(figsize=(10,6))
sns.histplot(train_df['dry_sales'], color='lightblue')
plt.title('Distribution of dry_sales')
plt.show()

#distribution of fresh sales
plt.figure(figsize=(10,6))
sns.histplot(train_df['fresh_sales'], color='lightgreen')
plt.title('Distribution of fresh_sales')
plt.show()

#distribution of clusters
plt.figure(figsize=(10,6))
sns.countplot(x='cluster_catgeory', data=train_df, color='orange')
plt.title('Frequency distribution for cluster_category')

"""#Multi-Variate Analysis"""

#Scatter plot of Luxury sales Vs Dry sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='dry_sales', data=train_df, color='lightpink')
plt.title('Scatter plot - Luxury sales Vs.  Dry sales')
plt.show()

#scatterplot for luxury sales Vs Fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='luxury_sales', y='fresh_sales', data=train_df, color='lightblue')
plt.title('Scatter plot - Luxury sales Vs.  Fresh sales')
plt.show()

#scatterplot for dry sales Vs fresh sales
plt.figure(figsize=(10,6))
sns.scatterplot(x='dry_sales', y='fresh_sales', data=train_df, color='lightgreen')
plt.title('Scatter plot - Dry sales Vs.  Fresh sales')
plt.show()

#luxury sales Vs clusters
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='luxury_sales', data=train_df, color='lightpink')

#dry sales Vs clusters
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='dry_sales', data=train_df, color='lightblue')

#Fresh sales Vs clusters
plt.figure(figsize=(12,6))
sns.boxplot(x='cluster_catgeory', y='fresh_sales', data=train_df, color='lightgreen')

#correlation matrix
corr_matrix = train_df.select_dtypes(include=['number']).corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation matrix')
plt.show()

#save the cleaned train data into a new csv file
train_df.to_csv('cleaned_train.csv', index=False)