# -*- coding: utf-8 -*-
"""DSPL Group B15 - Feature Engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_IHQMVB5GiF7N48j0czu5gYZHtKCn52
"""

#Import necessary packages
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

#Load cleaned datasets
train_df = pd.read_csv('cleaned_train.csv')
test_df = pd.read_csv('cleaned_test.csv')

"""# Feature Scaling

**Min-Max Scaling**
"""

#Apply Min-Max Scaling for distance-based models
min_max_scaler = MinMaxScaler()

#Min-Max Scaling - Train
train_df_minmax = train_df.copy()

scaled_train = train_df.select_dtypes(include=['number']).columns.tolist()

train_df[scaled_train] = min_max_scaler.fit_transform(train_df[scaled_train])

#Min-Max Scaling - Test
test_df_minmax = test_df.copy()

#Select numerical features for scaling, excluding 'Customer_ID'
scaled_test = test_df.select_dtypes(include=['number']).drop(columns=['Customer_ID'], errors='ignore').columns

#Convert the index object to a list
scaled_test = scaled_test.tolist()
test_df[scaled_test] = min_max_scaler.fit_transform(test_df[scaled_test])

#show the head of test dataset after scaling
test_df.head()

"""#Feature Selection

Label encoding for Categorical Variables
"""

#label encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

#all values in 'outlet_city' are converted to string before fitting
train_df['outlet_city'] = train_df['outlet_city'].astype(str)
test_df['outlet_city'] = test_df['outlet_city'].astype(str)

#Fit on the combined unique values from both train and test data
all_cities = pd.concat([train_df['outlet_city'], test_df['outlet_city']]).unique()
label_encoder.fit(all_cities)

#Transform the columns in both dataframes
train_df['outlet_city'] = label_encoder.transform(train_df['outlet_city'])
test_df['outlet_city'] = label_encoder.transform(test_df['outlet_city'])

train_df

#save the datasets after scaling and encoding
train_df.to_csv('scaled_train.csv', index=False)
test_df.to_csv('scaled_test.csv', index=False)